config/routes.rb
Rails.application.routes.draw do

  resources :home_icons
  get 'test/:level_id/:quiz_order' => 'quizzes#test'
  post 'check/:quiz_id' => "quizzes#check"
  resources :levels
  resources :quizzes
  resources :categories
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }

  post "/unsubscribe" =>"charges#unsubscribe"
  resources :charges
  resources :subcontents
  resources :articles
  root to: 'home#top'
  get 'home/about'
  get 'home/index'
  post '/addlist/:article_id' => "home#addlist"
  post 'deletelist/:article_id' => "home#deletelist"
  get 'all_users' => "home#all_users"
  get 'edit_user/:id' => "home#edit_user"
  post 'edit_user/:id' => "home#update_user"
  post 'delete/users/:id' => "home#delete_user"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord


  validates :title, length: {minimum:1, maximum:20}
  
  has_many :subcontents
  has_many :article_categories
  has_many :categories, through: :article_categories

  has_many :likes
  has_many :users, through: :likes

  mount_uploader :image, ImageUploader

  def self.search(search) #self.でクラスメソッドとしている
   if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
     #Article.where(['title LIKE ?', "%#{search}%"])
     titles = Article.arel_table
     Article.where(titles[:title].matches("%#{search}%"))
   else
     Article.all #全て表示。
   end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:edit, :update, :destroy]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.search(params[:search])
    @categories = Category.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :summary, :image, category_ids: [])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
    <% if article.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">close</span>
      </button>
        <p><%= pluralize(article.errors.count, "error") %> prohibited this subcontent from being saved:</p>
        <ul>
          <% article.errors.full_messages.each do |message| %>
            <li><h6><%= message %></h6></li>
          <% end %>
        </ul>
    </div>
    <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :summary %>
    <%= form.text_area :summary, class:"form-control"  %>
  </div>

  <div class="field form-group">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field form-group">
    <%= form.label :categories %><br>
     <%= form.collection_check_boxes :category_ids, Category.all, :id, :category_name do |cb| %>
     <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>


  <div class="actions">
    <%= form.submit :class => "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<p>
  <% @article.subcontents.order("sub_order").each do |s| %>
    <h5><%= s.sub_order%>. <%= s.name %></h5>
    <hr color="#000000" width="100%">

    <% if s.subcontent_type == true %>
      <div class="shadow-none p-3 mb-5 bg-dark rounded text-light"><%= s.content %></div>
    <% else %>
      <div class="shadow-none p-3 mb-5 bg-light rounded"><%= s.content %></div>
    <% end %>
    <div class="buttons">
      <%= link_to "Edit", edit_subcontent_path(s), class:"btn btn-outline-secondary" %>
      <%= link_to "Delete", subcontent_path(s),method: :delete, class:"btn btn-outline-danger" %>
    </div>
  <% end %>
</p>

<%= link_to 'New Subcontent', "/subcontents/new" %> |
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="text-center page-title">
  <h1>Articles & Categories</h1>
</div>

<div class="row">
    <div class="article-table col-8">
  <table class="table">
    <thead>
      <tr>
        <% if user_signed_in? && current_user.admin == true %>
        <th>#</th>
        <% end %>
        <th class="article-title-head"><h3>All Articles</h3></th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <% if user_signed_in? && current_user.admin == true %>
          <td><%= article.id %></td>
          <% end %>
          <td><div class="articles-index-title-wrapper"><%= link_to article.title, article, class:"article-title" %></div></br>
          <div class="summary"><%= article.summary %></div></td>
          <% if user_signed_in? && current_user.admin == true %>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>


<div class="category-table col-4 table-light">
  <table class="table">
    <thead>
      <tr>
        <th><h4>Categories</h4></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= link_to category.category_name, category, class:"btn btn-outline-success category-btn" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

</div>

<br>
<% if user_signed_in? && current_user.admin == true %>
  <%= link_to 'New Article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="text-center page-title">
<p>
  <h1><%= @article.title %></h1>
</p>
<% if user_signed_in? %>
  <% if Like.find_by(user_id: current_user.id, article_id: @article.id) %>
  <p>
    <%= link_to "Already Liked!","/deletelist/#{@article.id}" ,method: :post, class:"btn btn-secondary text-light" %>
  </p>
  <% else %>
  <p>
    <%= link_to "Add to Mylist","/addlist/#{@article.id}" ,method: :post, class:"btn btn-outline-primary" %>
  </p>
  <% end %>
<% end %>

<%= image_tag @article.image.to_s %></br>
  <div class="category_links">
    <% @article.categories.each do |c| %> <%= link_to c.category_name, category_path(c), class:"btn btn-outline-success" %> <% end %>
  </div>
</div>
<p>
  <% @article.subcontents.order("sub_order").each do |s| %>
    <h5><%= s.name %>
      <% if s.tips %>
        <button type="button" class="btn btn-outline-primary btn-lg" data-toggle="modal" data-target="#exampleModal">
          Tips
        </button>
      <% end %>
    </h5>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">

          <div class="modal-body">
           <%= s.tips %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>


    <hr color="#000000" width="100%">

    <% if s.subcontent_type == true %>
      <div class="shadow-none p-3 mb-5 bg-dark rounded text-light"><%= s.content %></div>
    <% else %>
      <div class="shadow-none p-3 mb-5 bg-light rounded"><%= s.content %></div>
    <% end %>
  <% end %>
</p>

<% if user_signed_in? && current_user.admin == true %>
<%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>