config/routes.rb
Rails.application.routes.draw do

  resources :home_icons
  get 'test/:level_id/:quiz_order' => 'quizzes#test'
  post 'check/:quiz_id' => "quizzes#check"
  resources :levels
  resources :quizzes
  resources :categories
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }

  post "/unsubscribe" =>"charges#unsubscribe"
  resources :charges
  resources :subcontents
  resources :articles
  root to: 'home#top'
  get 'home/about'
  get 'home/index'
  post '/addlist/:article_id' => "home#addlist"
  post 'deletelist/:article_id' => "home#deletelist"
  get 'all_users' => "home#all_users"
  get 'edit_user/:id' => "home#edit_user"
  post 'edit_user/:id' => "home#update_user"
  post 'delete/users/:id' => "home#delete_user"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :category_name, length: {minimum:1, maximum:10}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category_name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
    <% if category.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">close</span>
      </button>
        <p><%= pluralize(category.errors.count, "error") %> prohibited this subcontent from being saved:</p>
        <ul>
          <% category.errors.full_messages.each do |message| %>
            <li><h5><%= message %></h5></li>
          <% end %>
        </ul>
    </div>
    <% end %>

  <div class="field">
    <%= form.label :category_name %>
    <%= form.text_field :category_name, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="text-center page-title">
  <h1>Categories</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Category name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category_name %></td>
        <td><%= link_to 'Show', category, class:"btn btn-outline-success" %></td>
        <% if user_signed_in? && current_user.admin == true %>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? && current_user.admin == true %>
  <%= link_to 'New Category', new_category_path %>
<% end %>

app/views/categories/new.html.erb
<div class="text-center">
  <h1>New Category</h1>
</div>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path, class:"btn btn-outline-secondary" %>

app/views/categories/show.html.erb
<div class="page-title text-center"
  <p>
    <h1><%= @category.category_name %></h1>
  </p>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Articles</th>
    </tr>
  </thead>
  <tbody>
    <% @category.articles.each do |a| %>
    <tr>
      <td><%= link_to a.title, article_path(a), class:"btn btn-outline-success" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? && current_user.admin == true %>
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
<% end %>