config/routes.rb
Rails.application.routes.draw do

  resources :home_icons
  get 'test/:level_id/:quiz_order' => 'quizzes#test'
  post 'check/:quiz_id' => "quizzes#check"
  resources :levels
  resources :quizzes
  resources :categories
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }

  post "/unsubscribe" =>"charges#unsubscribe"
  resources :charges
  resources :subcontents
  resources :articles
  root to: 'home#top'
  get 'home/about'
  get 'home/index'
  post '/addlist/:article_id' => "home#addlist"
  post 'deletelist/:article_id' => "home#deletelist"
  get 'all_users' => "home#all_users"
  get 'edit_user/:id' => "home#edit_user"
  post 'edit_user/:id' => "home#update_user"
  post 'delete/users/:id' => "home#delete_user"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subcontent.rb
class Subcontent < ApplicationRecord

  belongs_to :article
  has_rich_text :content
end

app/controllers/subcontents_controller.rb
class SubcontentsController < ApplicationController
  before_action :set_subcontent, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_user

  # GET /subcontents
  # GET /subcontents.json
  def index
    @subcontents = Subcontent.all
  end

  # GET /subcontents/1
  # GET /subcontents/1.json
  def show
  end

  # GET /subcontents/new
  def new
    @subcontent = Subcontent.new
  end

  # GET /subcontents/1/edit
  def edit
  end

  # POST /subcontents
  # POST /subcontents.json
  def create
    @subcontent = Subcontent.new(subcontent_params)

    respond_to do |format|
      if @subcontent.save
        format.html { redirect_to "/articles/#{@subcontent.article_id}/edit", notice: 'Subcontent was successfully created.' }
        format.json { render :show, status: :created, location: @subcontent }
      else
        format.html { render :new }
        format.json { render json: @subcontent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcontents/1
  # PATCH/PUT /subcontents/1.json
  def update
    respond_to do |format|
      if @subcontent.update(subcontent_params)
        format.html { redirect_to "/articles/#{@subcontent.article_id}/edit", notice: 'Subcontent was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcontent }
      else
        format.html { render :edit }
        format.json { render json: @subcontent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcontents/1
  # DELETE /subcontents/1.json
  def destroy
    @subcontent.destroy
    respond_to do |format|
      format.html { redirect_to subcontents_url, notice: 'Subcontent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcontent
      @subcontent = Subcontent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcontent_params
      params.require(:subcontent).permit(:name, :subcontent_type, :article_id, :sub_order, :content, :tips)
    end
end

app/helpers/subcontents_helper.rb
module SubcontentsHelper
end

app/views/subcontents/_form.html.erb
<%= form_with(model: subcontent, local: true) do |form| %>
  <% if subcontent.errors.any? %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">close</span>
    </button>
      <p><%= pluralize(subcontent.errors.count, "error") %> prohibited this subcontent from being saved:</p>

      <ul>
        <% subcontent.errors.full_messages.each do |message| %>
          <li><h5><%= message %></h5></li>
        <% end %>
      </ul>
  </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :subcontent_type %>
    <%= form.check_box :subcontent_type %>
  </div>

  <div class="field form-group">
    <%= form.label :article_id %>
    <%= form.number_field :article_id %>
  </div>

  <div class="field form-group">
    <%= form.label :sub_order %>
    <%= form.number_field :sub_order %>
  </div>

  <div class="field form-group">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="field form-group">
    <%= form.label :tips %>
    <%= form.text_field :tips, class:"form-control" %>
  </div>


  <div class="actions">
    <%= form.submit :class=> "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/subcontents/edit.html.erb
<h1>Editing Subcontent</h1>

<%= render 'form', subcontent: @subcontent %>

<%= link_to 'Show', @subcontent %> |
<%= link_to 'Back', subcontents_path %>

app/views/subcontents/index.html.erb
<div class="text-center page-title">
<h1>Subcontents</h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcontents.each do |subcontent| %>
      <tr>
        <td><%= subcontent.name %></td>
        <td><%= subcontent.subcontent_type %></td>
        <td><%= subcontent.article_id %></td>
        <td><%= link_to 'Show', subcontent %></td>
        <td><%= link_to 'Edit', edit_subcontent_path(subcontent) %></td>
        <td><%= link_to 'Destroy', subcontent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcontent', new_subcontent_path %>

app/views/subcontents/new.html.erb
<div class="text-center">
<h1>New Subcontent</h1>
</div>
<%= render 'form', subcontent: @subcontent %>

<%= link_to 'Back', subcontents_path %>

app/views/subcontents/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @subcontent.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @subcontent.subcontent_type %>
</p>

<p>
  <strong>Article:</strong>
  <%= @subcontent.article_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @subcontent.sub_order %>
</p>

<p>
  <strong>Content:</strong>
  <%= @subcontent.content %>
</p>


<%= link_to 'Edit', edit_subcontent_path(@subcontent) %> |
<%= link_to 'Back', subcontents_path %>