config/routes.rb
Rails.application.routes.draw do

  resources :home_icons
  get 'test/:level_id/:quiz_order' => 'quizzes#test'
  post 'check/:quiz_id' => "quizzes#check"
  resources :levels
  resources :quizzes
  resources :categories
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }

  post "/unsubscribe" =>"charges#unsubscribe"
  resources :charges
  resources :subcontents
  resources :articles
  root to: 'home#top'
  get 'home/about'
  get 'home/index'
  post '/addlist/:article_id' => "home#addlist"
  post 'deletelist/:article_id' => "home#deletelist"
  get 'all_users' => "home#all_users"
  get 'edit_user/:id' => "home#edit_user"
  post 'edit_user/:id' => "home#update_user"
  post 'delete/users/:id' => "home#delete_user"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord


  validates :title, length: {minimum:1, maximum:20}
  
  has_many :subcontents
  has_many :article_categories
  has_many :categories, through: :article_categories

  has_many :likes
  has_many :users, through: :likes

  mount_uploader :image, ImageUploader

  def self.search(search) #self.でクラスメソッドとしている
   if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
     #Article.where(['title LIKE ?', "%#{search}%"])
     titles = Article.arel_table
     Article.where(titles[:title].matches("%#{search}%"))
   else
     Article.all #全て表示。
   end
  end

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

  belongs_to :article
  belongs_to :category
  
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :category_name, length: {minimum:1, maximum:10}
end

app/models/home_icon.rb
class HomeIcon < ApplicationRecord

  mount_uploader :icon_iamge, ImageUploader

end

app/models/level.rb
class Level < ApplicationRecord

  has_many :quizzes
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :article
  
end

app/models/quiz.rb
class Quiz < ApplicationRecord

  belongs_to :level
  
end

app/models/subcontent.rb
class Subcontent < ApplicationRecord

  belongs_to :article
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable



    def self.find_for_google_oauth2(auth)
      user = User.where(email: auth.info.email).first

    unless user
      user = User.create(name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20])
    end
      user
    end

    has_many :likes
    has_many :articles, through: :likes

    after_create :send_welcome_mail
    def send_welcome_mail
    UserMailer.user_welcome_mail(self).deliver
    end

    def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create

    # Amount in cents
    #@amount = 500

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    subscription = Stripe::Subscription.create({
    customer: customer.id,
    plan: "plan_G8FtqbcawJzjs9"
    })

    current_user.payment = true
    current_user.stripe_id = customer.id
    current_user.subscription_id = subscription.id
    current_user.purchase_date = subscription.created
    current_user.save

  #  charge = Stripe::Charge.create({
  #    customer: customer.id,
  #    amount: @amount,
  #    description: 'Rails Stripe customer',
  #    currency: 'jpy',
  #  })

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def unsubscribe

    subscription = Stripe::Subscription.update(
    current_user.subscription_id,
    {
      cancel_at_period_end: true,
    })

    current_user.payment = false
    current_user.cancel_date = subscription.canceled_at
    current_user.save

    redirect_to new_charge_path

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home_layout'
  before_action :admin_user, only: [:all_users, :edit_user, :update_user, :delete_user]

  def top
    @home_icons = HomeIcon.all
  end

  def all_users
    @users = User.all
  end

  def edit_user
    @user = User.find(params[:id])
  end

  def update_user
    @user = User.find_by(id: params[:id])
    @user.update(name: params[:name], email:params[:email], admin: params[:admin])
    redirect_to all_users_path
  end

  def delete_user
    @user = User.find_by(id:params[:id])
    @user.destroy
    redirect_to all_users_path
  end

  def about
  end

  def index
  end

  def addlist
    @like = Like.new
    @like.user_id = current_user.id
    @like.article_id = params[:article_id]
    @like.save
    redirect_to "/articles/#{@like.article_id}"
  end

  def deletelist
    @like = Like.find_by(user_id: current_user.id, article_id: params[:article_id])
    @like.destroy
    redirect_to "/articles/#{@like.article_id}"
  end

end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url, notice: 'Level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:level_name, :level_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource_class
     User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/home_icons_helper.rb
module HomeIconsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/subcontents_helper.rb
module SubcontentsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/home/about.html.erb
<div class="text-center">
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>
</div>

<iframe src="https://paiza.io/projects/e/LX2GWTWFs6gkqgyFF61XRg?theme=twilight" width="100%" height="500" scrolling="no" seamless="seamless"></iframe>

app/views/home/all_users.html.erb
<div class="text-center page-title">
  <h1>User List</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>User Name</th>
      <th>Email</th>
      <th>Admin</th>
      <th>Created at</th>
      <th>Payment</th>
      <th>Stripe ID</th>
      <th>Sub ID</th>
      <th>paid at</th>
      <th>canceld at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= user.created_at.strftime('%y-%m-%d') %></td>
        <td><%= user.payment %></td>
        <td><%= user.stripe_id %></td>
        <td><%= user.subscription_id %></td>

        <td>
          <% if user.purchase_date != nil %>
            <%= Time.at("#{user.purchase_date}".to_i).to_datetime.strftime('%y-%m-%d') %>
          <% else %>
            N/A
          <% end %>
        </td>

        <td><% if user.cancel_date != nil %>
              <%= Time.at("#{user.cancel_date}".to_i).to_datetime.strftime('%y-%m-%d') %>
            <% else %>
              N/A
          <% end %>
        </td>
        <td><%= link_to 'Show', root_path %></td>
        <td><%= link_to 'Edit',  "edit_user/#{user.id}"  %></td>
        <td><%= link_to 'Destroy', "delete/users/#{user.id}",method: :post, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/edit_user.html.erb
<h1>Edit User</h1>

<%= form_tag("/edit_user/#{@user.id}", method: :post) do %>
  <p>
  <%= label_tag :name %>
  <%= text_field_tag :name, "#{@user.name}",{class: "form-control"} %>
  </p>
  <p>
  <%= label_tag :email %>
  <%= text_field_tag :email, "#{@user.email}",{class: "form-control"}  %>
  </p>
  <p>
  <%= label_tag :admin %>
  <%= check_box_tag :admin, value=@user.admin,checked=@user.admin %>
  </p>
  <%= submit_tag %>
<% end %>

app/views/home/index.html.erb
<div class="text-center page-title">
  <h1>Your Articles</h1>
</div>
<% current_user.articles.each do |article| %>
  <%= link_to article.title, article_path(article), class:"btn btn-outline-success" %>
<% end %>

app/views/home/top.html.erb
<div class="text-center">
    <div class="home-top-wrapper">
      <h1>Learn Coding and Travel around the World</h1>
    </div>
</div>

<div class="text-center top-middle-wrapper">

  <% if !user_signed_in? %>
  <div class="intro-title"><h1 class="display-4">Code Around the Worldへようこそ！</h1></div>
  <p class="lead">このサイトは、初心者がウェブ開発を学ぶためのオンラインスクールです。</p>
  <p class="lead">知識０から実際のウェブアプリを作れるようになれます。</p>
  <p class="lead">プログラミングは全世界共通の言語です</p>
  <p class="lead">プログラミングを学び、世界への扉を開きましょう！</p>
  <hr class="my-4">
  <h4 class="regis-line">無料会員登録はこちら</h4>
  <button type="button" class="btn btn-outline-primary btn-lg" data-toggle="modal" data-target="#exampleModal">
    Signup
  </button>
  <div class="row card-deck">
       <div class="show_hero col col-sm-4 mx-auto" >
          <%= image_tag HomeIcon.first.icon_iamge.to_s, class:"card-img-top" %>
           <div class="hero_content">
              <a href="/test/1/1">
                <%= HomeIcon.first.icon_name %></br>
              Click Here!
              </a>
           </div>
       </div>
 </div>
  <% else %>
    <div class="row card-deck">
      <% @home_icons.each do |home_icon| %>
         <div class="show_hero col col-sm-4" >
            <%= image_tag home_icon.icon_iamge.to_s, class:"card-img-top" %>
             <div class="hero_content">
                <a href="<%= "/test/#{home_icon.level_id}/1" %>">
                  <%= home_icon.icon_name %></br>
                Click Here!
                </a>
             </div>
         </div>
       <% end %>
   </div>
 <% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Signup for Free</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>

          <div class="form-group"><%= f.label :email %><br />
          <%= f.email_field :email, class:"form-control" %></div>

          <div class="form-group"><%= f.label :name %><br />
          <%= f.text_field :name, class:"form-control"  %></div>

          <div class="form-group"><%= f.label :password %><br />
          <%= f.password_field :password, class:"form-control"  %></div>

          <div class="form-group"><%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, class:"form-control"  %></div>

          <div class="form-group"><%= f.submit "Sign up" ,class:"btn btn-outline-primary" %></div>
          <div class="form-group">
          <a href="/users/auth/google_oauth2">
          <p>Sign up with Google
          <i class="fab fa-google"></i>
          </p>
          </a>
          </div>
          <% end %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>

</div>